server.port=8080
spring.application.name=api-gateway
#spring.cloud.config.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Unique name registration with Eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.cloud.gateway.discovery.locator.enabled=true

# =========================
# Gateway Route Definitions
# =========================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
 
spring.cloud.gateway.routes[2].id=vehicle-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/vehicles/**

spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bookings/**
 
spring.cloud.gateway.routes[4].id=service-center
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/service-centers/**

spring.cloud.gateway.routes[5].id=invoice-center
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/invoices/**

# # =========================
# # CORS Configuration
# # =========================
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=Authorization,Content-Type